### ISSUE TITLE
关于缓存的自动清除

### ISSUE THREAD

**Issue by jcx70100** [smallcham/bdfs#1]
开发者您好，我想咨询一下，该程序挂载百度盘后，从挂载路径拷贝文件，缓存会存在那个路径下呢？有没有自动清除缓存的机制？比如设定只允许缓存占用空间为2G，超出后会自动清理已下载不用的缓存？

**Comment by smallcham** [comment]
> 开发者您好，我想咨询一下，该程序挂载百度盘后，从挂载路径拷贝文件，缓存会存在那个路径下呢？有没有自动清除缓存的机制？比如设定只允许缓存占用空间为2G，超出后会自动清理已下载不用的缓存？

默认会放到 /tmp/.bdfs/.data 目录， /tmp 属于内存文件系统，理论上重启后自动删除， 缓存目录可以在 model/enum.py 里面配

**Comment by jcx70100** [comment]
好的，感谢您的回复。
查找相关资料发现不同的linux发行版对/tmp目录的清除策略稍有差异，最后我是通过设定`tmpwatch`来实现自动清除一段时间内没访问的文件的：
`tmpwatch 24 /tmp/ #清除24小时内未访问的文件，配合crontab执行`

还有一个问题想咨询一下，现在部署后发现速度不是很快，svip账户下载几十兆的小文件，速度在100-300kb左右，您那边使用是这个速度吗？有么有可能引入aria2作为下载工具提升下载速度呢？

**Comment by smallcham** [comment]
嗯，我这边使用速度也挺慢的，这个项目在考虑用其它语言重写优化，目前不会做变动。

**Comment by jcx70100** [comment]
好的，期待新的项目哈，感谢您写的这个项目，至少的linux端解决了无法挂载百度盘的噩梦。
